# =======================  config.yaml  =======================
#  必要な項目はすべてここで定義。train_vc.py が参照します。
# ============================================================

# ────────────────────────────────
#  データセット関連
# ────────────────────────────────
train_csv:  train.csv          # 学習用 CSV
val_csv:    val.csv            # 検証用 CSV
stats_tensor: stats.pt    # (mean, std) を格納した .pt

# ────────────────────────────────
#  データローダ
# ────────────────────────────────
batch_size:  8
num_workers: 4

# ────────────────────────────────
#  サンプリング・HuBERT 設定
# ────────────────────────────────
sr:   16000        # 最終出力サンプリングレート
hop:  320          # HuBERT 20 ms → 16 kHz で 320 サンプル

# ────────────────────────────────
#  モデル・損失ハイパーパラメータ
# ────────────────────────────────
lr_g: 0.0002       # Generator 学習率
lr_d: 0.0002       # Discriminator 学習率

lambda_fm:  2.0    # Feature-Matching 重み
lambda_mag: 1.0    # STFT magnitude L1
lambda_sc:  1.0    # STFT spectral-convergence

# ────────────────────────────────
#  学習率スケジューラ (StepLR)
# ────────────────────────────────
sched_gamma: 0.5   # 学習率減衰率
sched_step:  200   # 何 epoch ごとに減衰

# ────────────────────────────────
#  学習ループ
# ────────────────────────────────
max_epochs: 400
gpus:        1     # 0 → CPU / 1→ single GPU / N→ multi GPU

# ────────────────────────────────
#  ロギング・チェックポイント
# ────────────────────────────────
work_dir: /media/akio/hdd1/rvc/models/test/logs            # Lightning の default_root_dir
log_dir:  /media/akio/hdd1/rvc/models/test/logs/tb         # TensorBoard 保存先
ckpt_dir: /media/akio/hdd1/rvc/models/test/logs/ckpt       # ModelCheckpoint が .ckpt を置く先
# ModelCheckpoint は train_vc.py 内で固定：
#   monitor=loss_g/epoch,  save_last: true,  save_top_k: 1,  every_n_epochs: 50
# ============================================================
